version: '3.8'

services:
  # Node.js Application (connects to existing PostgreSQL)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: productivity-hub-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3070}
      # Use your existing PostgreSQL connection details
      DB_HOST: ${DB_HOST:-192.168.1.4}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-productivity-hub}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-epaps0991g}
    ports:
      - "${PORT:-3070}:3070"
    # Use host network to access existing PostgreSQL
    network_mode: bridge
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3070/api/notes', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
